//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlohaNotificationDAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomListValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomListValue()
        {
            this.Definitions = new HashSet<Definition>();
            this.Definitions1 = new HashSet<Definition>();
            this.PayrollProcessBatches = new HashSet<PayrollProcessBatch>();
        }
    
        public int CustomListValue_Id { get; set; }
        public int CustomList_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public bool IsEditable { get; set; }
        public bool IsActive { get; set; }
        public bool IsSystemDefined { get; set; }
        public bool IsRemoved { get; set; }
        public Nullable<int> CreatedBy_Id { get; set; }
        public Nullable<long> CreatedOn { get; set; }
        public Nullable<int> LastEditedBy_Id { get; set; }
        public Nullable<long> LastEditedOn { get; set; }
        public System.Guid Subscription_Id { get; set; }
        public System.Guid InternalKey { get; set; }
        public byte[] InternalHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Definition> Definitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Definition> Definitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollProcessBatch> PayrollProcessBatches { get; set; }
    }
}
