//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlohaNotificationDAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parameter()
        {
            this.ParameterValues = new HashSet<ParameterValue>();
        }
    
        public int Parameter_Id { get; set; }
        public int Definition_Id { get; set; }
        public string ParameterName { get; set; }
        public string ParameterCode { get; set; }
        public string ParameterPrefixdescription { get; set; }
        public string ParameterPostfixdescription { get; set; }
        public int Parameter_CL_Id { get; set; }
        public bool IsRemoved { get; set; }
        public System.Guid Subscription_Id { get; set; }
        public Nullable<bool> IsMultiSelect { get; set; }
    
        public virtual Definition Definition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterValue> ParameterValues { get; set; }
    }
}
