//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlohaNotificationDAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollProcessBatch
    {
        public int PayrollProcessBatch_Id { get; set; }
        public Nullable<long> PayrollPeriodStartDate { get; set; }
        public Nullable<long> PayrollPeriodEndDate { get; set; }
        public Nullable<int> PayrollFrequency_CLV_Id { get; set; }
        public Nullable<int> Createdby_Id { get; set; }
        public Nullable<long> CreatedOn { get; set; }
        public System.Guid Subscription_Id { get; set; }
        public bool IsRemoved { get; set; }
        public System.Guid InternalKey { get; set; }
        public string ExternalKey { get; set; }
        public byte[] InternalHash { get; set; }
    
        public virtual CustomListValue CustomListValue { get; set; }
    }
}
